apiVersion: v1
kind: Service
metadata:
  name: exercise1
  labels:
    app: nginx-server
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: nginx:1.19.4
          ports:
            - containerPort: 80
          resources:
          requests:
            memory: '256Mi'
            cpu: '100m'
          limits:
            memory: '256Mi'
            cpu: '100m'
