apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: nginx-server
spec:
  type: LoadBalancer
  clusterIP: 10.1.1.2
  selector:
    ports:
      - protocol: TCP
      targetPort: 80
      port: 80
