apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
    app: nginx-server
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
